#!/bin/sh

echo "Waiting for Redis to start..."
sleep 5 

echo "Seeding Redis with default weather data..."

redis-cli -h redis set Dhaka '{"temp":"33°C","humidity":"70%","precipitation":"10%","status":"Sunny"}'
redis-cli -h redis set Tokyo '{"temp":"22°C","humidity":"60%","precipitation":"0%","status":"Cloudy"}'
redis-cli -h redis set London '{"temp":"15°C","humidity":"80%","precipitation":"50%","status":"Rainy"}'
redis-cli -h redis set NewYork '{"temp":"18°C","humidity":"65%","precipitation":"20%","status":"Windy"}'
redis-cli -h redis set Sydney '{"temp":"25°C","humidity":"55%","precipitation":"5%","status":"Sunny"}'
redis-cli -h redis set Beijing '{"temp":"28°C","humidity":"45%","precipitation":"5%","status":"Smoggy"}'
redis-cli -h redis set Shanghai '{"temp":"30°C","humidity":"75%","precipitation":"15%","status":"Humid"}'
redis-cli -h redis set Mumbai '{"temp":"32°C","humidity":"85%","precipitation":"30%","status":"Hot"}'
redis-cli -h redis set Delhi '{"temp":"35°C","humidity":"40%","precipitation":"0%","status":"Dry"}'
redis-cli -h redis set Bangkok '{"temp":"34°C","humidity":"80%","precipitation":"40%","status":"Scattered Storms"}'
redis-cli -h redis set Singapore '{"temp":"31°C","humidity":"90%","precipitation":"60%","status":"Thunderstorms"}'
redis-cli -h redis set Dubai '{"temp":"39°C","humidity":"30%","precipitation":"0%","status":"Blazing Sun"}'
redis-cli -h redis set Istanbul '{"temp":"24°C","humidity":"65%","precipitation":"10%","status":"Partly Cloudy"}'
redis-cli -h redis set Seoul '{"temp":"26°C","humidity":"70%","precipitation":"25%","status":"Drizzle"}'
redis-cli -h redis set Jakarta '{"temp":"30°C","humidity":"85%","precipitation":"50%","status":"Rainy"}'
redis-cli -h redis set Manila '{"temp":"29°C","humidity":"75%","precipitation":"20%","status":"Partly Cloudy"}'
redis-cli -h redis set Seoul '{"temp":"26°C","humidity":"70%","precipitation":"25%","status":"Drizzle"}'
redis-cli -h redis set HongKong '{"temp":"28°C","humidity":"80%","precipitation":"30%","status":"Thunderstorms"}'
redis-cli -h redis set London '{"temp":"15°C","humidity":"80%","precipitation":"50%","status":"Rainy"}'
redis-cli -h redis set Paris '{"temp":"18°C","humidity":"75%","precipitation":"40%","status":"Light Rain"}'
redis-cli -h redis set Berlin '{"temp":"17°C","humidity":"70%","precipitation":"30%","status":"Overcast"}'
redis-cli -h redis set Madrid '{"temp":"29°C","humidity":"35%","precipitation":"0%","status":"Sunny"}'
redis-cli -h redis set Rome '{"temp":"27°C","humidity":"50%","precipitation":"5%","status":"Clear"}'
redis-cli -h redis set Amsterdam '{"temp":"16°C","humidity":"85%","precipitation":"60%","status":"Rainy"}'
redis-cli -h redis set Moscow '{"temp":"12°C","humidity":"60%","precipitation":"20%","status":"Chilly"}'
redis-cli -h redis set Vienna '{"temp":"20°C","humidity":"65%","precipitation":"15%","status":"Mostly Sunny"}'
redis-cli -h redis set Prague '{"temp":"19°C","humidity":"70%","precipitation":"25%","status":"Cloudy"}'
redis-cli -h redis set Athens '{"temp":"31°C","humidity":"40%","precipitation":"0%","status":"Hot"}'
redis-cli -h redis set NewYork '{"temp":"18°C","humidity":"65%","precipitation":"20%","status":"Windy"}'
redis-cli -h redis set LosAngeles '{"temp":"25°C","humidity":"50%","precipitation":"0%","status":"Sunny"}'
redis-cli -h redis set Chicago '{"temp":"14°C","humidity":"75%","precipitation":"45%","status":"Rainy"}'
redis-cli -h redis set Toronto '{"temp":"13°C","humidity":"80%","precipitation":"50%","status":"Stormy"}'
redis-cli -h redis set Vancouver '{"temp":"12°C","humidity":"85%","precipitation":"70%","status":"Heavy Rain"}'
redis-cli -h redis set MexicoCity '{"temp":"21°C","humidity":"60%","precipitation":"10%","status":"Partly Cloudy"}'
redis-cli -h redis set Miami '{"temp":"30°C","humidity":"85%","precipitation":"55%","status":"Humid"}'
redis-cli -h redis set SanFrancisco '{"temp":"17°C","humidity":"70%","precipitation":"0%","status":"Foggy"}'
redis-cli -h redis set LasVegas '{"temp":"38°C","humidity":"15%","precipitation":"0%","status":"Scorching"}'
redis-cli -h redis set Montreal '{"temp":"11°C","humidity":"75%","precipitation":"40%","status":"Drizzle"}'
redis-cli -h redis set Rio '{"temp":"28°C","humidity":"75%","precipitation":"20%","status":"Partly Cloudy"}'
redis-cli -h redis set BuenosAires '{"temp":"15°C","humidity":"65%","precipitation":"10%","status":"Cool"}'
redis-cli -h redis set Lima '{"temp":"19°C","humidity":"85%","precipitation":"5%","status":"Misty"}'
redis-cli -h redis set Bogota '{"temp":"16°C","humidity":"80%","precipitation":"60%","status":"Rainy"}'
redis-cli -h redis set Santiago '{"temp":"14°C","humidity":"45%","precipitation":"0%","status":"Clear"}'
redis-cli -h redis set Cairo '{"temp":"34°C","humidity":"25%","precipitation":"0%","status":"Hot"}'
redis-cli -h redis set CapeTown '{"temp":"18°C","humidity":"70%","precipitation":"30%","status":"Windy"}'
redis-cli -h redis set Nairobi '{"temp":"22°C","humidity":"80%","precipitation":"45%","status":"Thunderstorms"}'
redis-cli -h redis set Lagos '{"temp":"30°C","humidity":"90%","precipitation":"65%","status":"Humid"}'
redis-cli -h redis set Johannesburg '{"temp":"17°C","humidity":"50%","precipitation":"10%","status":"Sunny"}'
redis-cli -h redis set Sydney '{"temp":"25°C","humidity":"55%","precipitation":"5%","status":"Sunny"}'
redis-cli -h redis set Melbourne '{"temp":"14°C","humidity":"75%","precipitation":"40%","status":"Rainy"}'
redis-cli -h redis set Auckland '{"temp":"16°C","humidity":"80%","precipitation":"50%","status":"Showers"}'
redis-cli -h redis set Brisbane '{"temp":"27°C","humidity":"65%","precipitation":"15%","status":"Partly Cloudy"}'
redis-cli -h redis set Perth '{"temp":"29°C","humidity":"40%","precipitation":"0%","status":"Clear"}'

echo "Seeding complete!"
