services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  thermo:
    build: ./thermo
    ports:
      - "8081:8081"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379

  throttle:
    build: ./throttle
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis-seed:
    image: redis
    depends_on:
      - redis
    entrypoint: ["/bin/sh", "-c", "/init/seed_redis.sh"]
    volumes:
      - ./init:/init
